In [2]:
# Importa os dados do arquivo 

df = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv',delimiter=";", encoding="latin1")

# Exibe o conteúdo completo do DataFrame 'pesquisa' no console.
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [3]:
Rio_de_janeiro = [
   "Rio de Janeiro"
]

In [ ]:

municipio = df.loc[(df['munic'].isin(Rio_de_janeiro))]
municipio

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36528,40,8,2025,2025m08,9,2,Rio de Janeiro,3304557,Capital,2,...,3.0,0.0,39,5,0,0,0,0,675,2
36529,41,8,2025,2025m08,18,2,Rio de Janeiro,3304557,Capital,0,...,3.0,0.0,47,3,0,0,0,0,715,2
36530,42,8,2025,2025m08,31,2,Rio de Janeiro,3304557,Capital,1,...,13.0,2.0,92,3,2,0,0,0,1225,2
36531,43,8,2025,2025m08,27,2,Rio de Janeiro,3304557,Capital,1,...,7.0,0.0,87,7,1,0,0,0,688,2
36532,44,8,2025,2025m08,3,1,Rio de Janeiro,3304557,Capital,1,...,13.0,0.0,43,5,1,0,0,0,808,2

In [5]:
df_municipio = municipio.groupby(['cisp'])['estelionato'].sum().reset_index()
df_municipio

    cisp  estelionato
0      1        27293
1      4         6918
2      5        21417
3      6         7226
4      7         2182
5      9        17092
6     10        19249
7     11         1293
8     12        21174
9     13        11509
10    14        18586
11    15        10409
12    16        41003
13    17         6998
14    18        10130
15    19        20340
16    20        13490
17    21        17909
18    22        13293
19    23        14311
20    24         8637
21    25         7523
22    26         8369
23    27        13830
24    28        10632
25    29        17796
26    30         8875
27    31         6443
28    32        32570
29    33        15389
30    34        23101
31    35        38234
32    36        15234
33    37        15427
34    38        10100
35    39         8129
36    40         6726
37    41        12936
38    42        19272
39    43         6065
40    44         6661
41    45           98

In [14]:
q3 = np.percentile(df_municipio["estelionato"], 75)
print(f'Terceiro quartil (Q3) = {q3}')

Terceiro quartil (Q3) = 18416.75

In [15]:
df_final = df_municipio.loc[df_municipio["estelionato"] > q3]
df_final

    cisp  estelionato
0      1        27293
2      5        21417
6     10        19249
8     12        21174
10    14        18586
12    16        41003
15    19        20340
28    32        32570
30    34        23101
31    35        38234
38    42        19272

In [16]:
df_final.to_csv('Rio de janeiro_estelionato.csv', sep=";", index=  False)

In [19]:
array_df_municipio = np.array(df_municipio["estelionato"])

# Mediana (valor central)
mediana_anterior = np.median(array_df_municipio)
media_anterior = np.mean(array_df_municipio)

# Quartis
q1_anterior = np.percentile(array_df_municipio, 25)  # Primeiro quartil
q2_anterior = np.percentile(array_df_municipio, 50)  # Terceiro quartil
q3_anterior = np.percentile(array_df_municipio, 75)  # Terceiro quartil
distancia_anterior = (media_anterior - mediana_anterior) / mediana_anterior
iqr_anterior = q3_anterior - q1_anterior
limite_superior_total = q3_anterior + (1.5*iqr_anterior)
limite_inferior_total = q1_anterior - (1.5*iqr_anterior)

print(f'media {media_anterior}')
print(f'mediana {mediana_anterior}')
print(f'distancia {distancia_anterior*100}%')

media 14139.738095238095
mediana 13114.5
distancia 7.817591942034355%

In [20]:

Outliers_superior = df_final.loc[df_final['estelionato'] >= limite_superior_total]
print(Outliers_superior)

    cisp  estelionato
12    16        41003
31    35        38234

In [22]:
Outliers_superior.to_csv('Outliers_superior_Estelionatos.csv', sep=";", index=  False)