In [53]:
# importa a biblioteca pandas e dá o apelido 'pd'
import pandas as pd  

# importa a biblioteca numpy e dá o apelido 'np'
import numpy as np

In [65]:



#Aqui importamos a biblioteca NumPy, que é muito usada em Python para cálculos numéricos,
import numpy as np


#Esse array representa um conjunto de dados que vamos analisar estatisticamente.
dados = np.array([12, 15, 17, 20, 22, 25, 28, 30, 35, 40])

# Mediana (valor central)
mediana = np.median(dados)

# Quartis
q1 = np.percentile(dados, 25)  # Primeiro quartil
q2 = np.percentile(dados, 50)  # Segundo quartil (igual à mediana)
q3 = np.percentile(dados, 75)  # Terceiro quartil

print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil  (Q2, Mediana): {q2}')
print(f'Mediana {mediana}')
print(f'Terceio quartil  (Q3): {q3}')

Primeiro quartil (Q1): 17.75
Segundo quartil  (Q2, Mediana): 23.5
Mediana 23.5
Terceio quartil  (Q3): 29.5

In [66]:
# Importa os dados do arquivo CSV 'pesquisa_satisfacao.csv' 

pesquisa = pd.read_csv('pesquisa_satisfacao.csv', sep=';')

# Exibe o conteúdo completo do DataFrame 'pesquisa' no console.
print(pesquisa)

         Cliente Satisfação  Tempo de Espera (min)
0         Naruto       Alta                      8
1           Goku       Alta                     10
2         Vegeta      Média                     17
3         Sasuke       Alta                      8
4         Madara      Média                     15
5          Luffy      Baixa                      5
6           Zoro       Alta                     22
7          Sanji      Baixa                     26
8         Yusuke      Baixa                     14
9         Kurama      Média                      8
10           Gon      Média                     12
11          Eren      Média                     28
12        Mikasa       Alta                      6
13         Light       Alta                     10
14             L       Alta                     19
15  Peter Parker      Baixa                     21
16   Bruce Wayne       Alta                     18
17        Thanos      Média                     19
18       Edmundo      Baixa                     13
19       Vegetti      Média                     19

In [67]:
tempo_espera_array = np.array(read["Tempo de Espera (min)"])

# Mediana (valor central)
mediana = np.median(tempo_espera_array)

# Quartis
q1 = np.percentile(tempo_espera_array, 25)  # Primeiro quartil
q2 = np.percentile(tempo_espera_array, 50)  # Segundo quartil (igual à mediana)
q3 = np.percentile(tempo_espera_array, 75)  # Terceiro quartil

print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil  (Q2, Mediana): {q2}')
print(f'Mediana {mediana}')
print(f'Terceio quartil  (Q3): {q3}')

Primeiro quartil (Q1): 9.5
Segundo quartil  (Q2, Mediana): 14.5
Mediana 14.5
Terceio quartil  (Q3): 19.0

In [68]:
# Seleciona todas as linhas do DataFrame 'pesquisa'
# em que a coluna 'Tempo de Espera (min)' é maior ou igual ao valor de Q3 (terceiro quartil).
pequisa_maiores = pesquisa.loc[pesquisa['Tempo de Espera (min)'] >= q3]

# Ordena o DataFrame 'pequisa_maiores' pela coluna 'Tempo de Espera (min)'
# em ordem decrescente (do maior para o menor tempo de espera).
pequisa_maiores.sort_values(by="Tempo de Espera (min)", ascending=False)

         Cliente Satisfação  Tempo de Espera (min)
11          Eren      Média                     28
7          Sanji      Baixa                     26
6           Zoro       Alta                     22
15  Peter Parker      Baixa                     21
14             L       Alta                     19
17        Thanos      Média                     19
19       Vegetti      Média                     19

In [69]:
# Ordena o DataFrame 'pesquisa' usando como critério a coluna "Tempo de Espera (min)".
# O parâmetro ascending=False indica que a ordenação será em ordem decrescente,
# ou seja, do maior tempo de espera para o menor.
pesquisa.sort_values(by="Tempo de Espera (min)", ascending=False)

         Cliente Satisfação  Tempo de Espera (min)
11          Eren      Média                     28
7          Sanji      Baixa                     26
6           Zoro       Alta                     22
15  Peter Parker      Baixa                     21
17        Thanos      Média                     19
19       Vegetti      Média                     19
14             L       Alta                     19
16   Bruce Wayne       Alta                     18
2         Vegeta      Média                     17
4         Madara      Média                     15
8         Yusuke      Baixa                     14
18       Edmundo      Baixa                     13
10           Gon      Média                     12
13         Light       Alta                     10
1           Goku       Alta                     10
0         Naruto       Alta                      8
3         Sasuke       Alta                      8
9         Kurama      Média                      8
12        Mikasa       Alta                      6
5          Luffy      Baixa                      5

In [70]:
# 01 Atividade: Filtre os dados com satisfação alta.

satisfacao_alta = pesquisa.loc[pesquisa['Satisfação']== 'Alta']
satisfacao_alta

        Cliente Satisfação  Tempo de Espera (min)
0        Naruto       Alta                      8
1          Goku       Alta                     10
3        Sasuke       Alta                      8
6          Zoro       Alta                     22
12       Mikasa       Alta                      6
13        Light       Alta                     10
14            L       Alta                     19
16  Bruce Wayne       Alta                     18

In [73]:
# 02 Atividade: Calcule os quartis e a mediana para esse grupo.


array_alta = np.array(satisfacao_alta['Tempo de Espera (min)'])
array_alta

# Mediana (valor central)
mediana = np.median(array_alta)

# Quartis
q1 = np.percentile(array_alta, 25)  # Primeiro quartil
q2 = np.percentile(array_alta, 50)  # Segundo quartil (igual à mediana)
q3 = np.percentile(array_alta, 75)  # Terceiro quartil

print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil  (Q2, Mediana): {q2}')
print(f'Mediana {mediana}')
print(f'Terceio quartil  (Q3): {q3}')

Primeiro quartil (Q1): 8.0
Segundo quartil  (Q2, Mediana): 10.0
Mediana 10.0
Terceio quartil  (Q3): 18.25

In [77]:
# 03 Atividade: Compare com os dados gerais.

mediana_geral = np.array(read["Tempo de Espera (min)"])

# Mediana (valor central)
mediana = np.median(tempo_espera_array)

# Quartis
q1_geral  = np.percentile(tempo_espera_array, 25)  # Primeiro quartil
q2_geral  = np.percentile(tempo_espera_array, 50)  # Segundo quartil (igual à mediana)
q3_geral = np.percentile(tempo_espera_array, 75)  # Terceiro quartil

print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil  (Q2, Mediana): {q2}')
print(f'Mediana {mediana}')
print(f'Terceio quartil  (Q3): {q3}')

print ('*************************************')

print(f'Primeiro quartil (Q1): {q1_geral}')
print(f'Segundo quartil  (Q2, Mediana): {q2_geral}')
print(f'Mediana {mediana}')
print(f'Terceio quartil  (Q3): {q3_geral}')

Primeiro quartil (Q1): 8.0
Segundo quartil  (Q2, Mediana): 10.0
Mediana 14.5
Terceio quartil  (Q3): 18.25
*************************************
Primeiro quartil (Q1): 9.5
Segundo quartil  (Q2, Mediana): 14.5
Mediana 14.5
Terceio quartil  (Q3): 19.0

    Desafio analítico 01

Utilizando a base de
dados BaseDPEvolucaoMensalCisp.csv, que
contém a evolução mensal das ocorrências
registradas por delegacia, sua missão é:

#1.Filtrar os dados relacionados a furtos de celulares.

#2.Agrupar os dados por delegacia, somando o total
de furtos registrados.

#3.Aplicar análise estatística descritiva:
•Calcular a média, mediana e os quartis das
ocorrências por delegacia.

#4.Identificar:
•As delegacias que representam os 25% com
menor número de furtos (primeiro quartil).
•As delegacias que representam os 25% com
maior número de furtos de celular.

In [63]:
ispdados = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv', sep=';',encoding='latin1')
ispdados

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36624,159,8,2025,2025m08,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,5.0,0.0,16,0,0,0,0,0,148,2
36625,165,8,2025,2025m08,33,5,Mangaratiba,3302601,Interior,0,...,5.0,0.0,21,2,0,0,0,0,179,2
36626,166,8,2025,2025m08,33,5,Angra dos Reis,3300100,Interior,3,...,11.0,3.0,63,8,0,0,0,0,595,2
36627,167,8,2025,2025m08,43,5,Paraty,3303807,Interior,0,...,3.0,0.0,13,2,0,1,0,0,234,2
36628,168,8,2025,2025m08,28,5,Rio Claro,3304409,Interior,1,...,1.0,0.0,5,0,0,0,0,0,50,2

In [64]:

# 1. Filtrar os dados relacionados a furtos de celulares
furtos_celulares = ispdados.sort_values(by ="furto_celular")
furtos_celulares

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
27716,156,3,2020,2020m03,11,7,Santa Maria Madalena,3304607,Interior,0,...,1.0,0.0,1,1,0,0,0,0,16,3
27717,157,3,2020,2020m03,11,7,Trajano de Morais,3305901,Interior,0,...,1.0,0.0,1,0,0,0,0,0,12,3
27718,158,3,2020,2020m03,11,7,Bom Jardim,3300506,Interior,0,...,1.0,0.0,7,0,0,0,0,0,42,3
27719,159,3,2020,2020m03,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,3.0,0.0,15,0,0,0,0,0,70,3
27723,168,3,2020,2020m03,28,5,Rio Claro,3304409,Interior,0,...,1.0,0.0,4,0,0,0,0,0,32,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20187,42,9,2015,2015m09,31,2,Rio de Janeiro,3304557,Capital,0,...,6.0,1.0,79,3,2,0,0,0,2165,3
36089,12,5,2025,2025m05,19,1,Rio de Janeiro,3304557,Capital,0,...,15.0,0.0,28,7,0,0,0,0,1883,3
35675,9,2,2025,2025m02,2,1,Rio de Janeiro,3304557,Capital,3,...,4.0,3.0,42,5,0,0,0,0,1808,3
31709,16,9,2022,2022m09,31,2,Rio de Janeiro,3304557,Capital,2,...,14.0,4.0,91,10,1,0,0,0,3036,3
34997,16,9,2024,2024m09,31,2,Rio de Janeiro,3304557,Capital,3,...,18.0,6.0,98,13,0,0,0,0,3185,3

In [87]:
# 2. Agrupar os dados por delegacia (cisp), somando os furtos de celular

delegacias = furtos_celulares.groupby('cisp')['furto_celular'].sum().reset_index()
delegacias

     cisp  furto_celular
0       1          14789
1       4          13093
2       5          22494
3       6           6072
4       7           1425
..    ...            ...
133   159            450
134   165           1216
135   166           2531
136   167            483
137   168            119

[138 rows x 2 columns]

In [66]:
#3.Aplicar análise estatística descritiva:•Calcular a média, mediana e os quartis dasocorrências por delegacia.

array_furtos_celular = np.array(delegacias["furto_celular"])

# Mediana (valor central)
mediana = np.median(array_furtos_celular)

# Quartis
q1  = np.percentile(array_furtos_celular, 25)  # Primeiro quartil
q2  = np.percentile(array_furtos_celular, 50)  # Segundo quartil (igual à mediana)
q3 = np.percentile(array_furtos_celular, 75)  # Terceiro quartil

print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil  (Q2, Mediana): {q2}')
print(f'Mediana {mediana}')
print(f'Terceio quartil  (Q3): {q3}')

Primeiro quartil (Q1): 445.5
Segundo quartil  (Q2, Mediana): 1609.5
Mediana 1609.5
Terceio quartil  (Q3): 4377.25

In [67]:
#4.Identificar:•As delegacias que representam os 25% com menor número de furtos (primeiro quartil).
#•As delegacias que representam os 25% com maior número de furtos de celular.

array_furtos_celular = np.array(delegacias["furto_celular"])

# Mediana (valor central)
mediana = np.median(array_furtos_celular)


# Quartis
q1  = np.percentile(array_furtos_celular, 25)  # Primeiro quartil
q3 = np.percentile(array_furtos_celular, 75)  # Terceiro quartil

print(f'Primeiro quartil (Q1): {q1}')
print(f'Terceio quartil  (Q3): {q3}')

Primeiro quartil (Q1): 445.5
Terceio quartil  (Q3): 4377.25

    Desafio analítico 02

O Secretário de Segurança Pública do Estado solicitou uma análise acerca das ocorrências estelionato registradas por
município. O objetivo é identificar àqueles municípios que representam os 25% que mais ocorreram tal fato. Além
disso, o Secretário quer identificar aqueles que menos ocorreram.

In [ ]:
# Agrupar os dados por município (munic), somando os estelionatos

estelionato_municipio = ispdados.groupby('munic')['estelionato'].sum().reset_index()
estelionato_municipio

                 munic  estelionato
0       Angra dos Reis         7979
1             Araruama         7819
2   Armação dos Búzios         3213
3      Arraial do Cabo         1290
4          Barra Mansa         6155
..                 ...          ...
85         Teresópolis        10015
86   Trajano de Morais          174
87             Valença         2087
88           Vassouras         1423
89       Volta Redonda        15597

[90 rows x 2 columns]

In [88]:
array_estelinato = np.array(estelionato_municipio["estelionato"])

# Mediana (valor central)
mediana = np.median(array_estelinato)


# Quartis
q1  = np.percentile(array_estelinato, 25)  # Primeiro quartil
q3 = np.percentile(array_estelinato, 75)  # Terceiro quartil

print(f'Primeiro quartil (Q1): {q1}')
print(f'Terceio quartil  (Q3): {q3}')

Primeiro quartil (Q1): 625.0
Terceio quartil  (Q3): 7010.5